services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./app/:/usr/src/app/
    ports:
    - 8080:8000
    env_file:
      - ./GLSR_Gym/.env.staging
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./GLSR_Gym/.env.prod.db

volumes:
  postgres_data: